import type { StaffRole } from "@/types/database";
import { ALL_PERMISSIONS, type Permission } from "@/config/rbac-permissions";

export const ROLE_PERMISSIONS: Record<StaffRole, Permission[]> = {
  super_admin: ALL_PERMISSIONS,
  admin: ALL_PERMISSIONS,
  manager: [
    "dashboard.view",
    "products.view",
    "products.edit",
    "products.markup",
    "orders.view",
    "orders.manage",
    "customers.view",
    "customers.manage",
    "support.view",
    "support.manage",
    "marketing.view",
    "finance.view",
    "inventory.view",
    "inventory.manage",
    "returns.view",
    "returns.manage",
    "procurement.view",
    "procurement.manage",
    "analytics.view",
    "searches.view",
    "settings.view",
    "activity.view",
  ],
  support_agent: [
    "dashboard.view",
    "orders.view",
    "customers.view",
    "customers.reset_password",
    "support.view",
    "support.manage",
    "returns.view",
    "returns.manage",
  ],
  marketing: [
    "dashboard.view",
    "products.view",
    "products.edit",
    "marketing.view",
    "marketing.manage",
    "analytics.view",
    "searches.view",
  ],
  fulfillment: [
    "dashboard.view",
    "orders.view",
    "orders.manage",
    "products.view",
    "inventory.view",
    "inventory.manage",
    "procurement.view",
    "procurement.manage",
    "searches.view",
  ],
  finance: [
    "dashboard.view",
    "orders.view",
    "finance.view",
    "finance.manage",
    "returns.view",
    "returns.manage",
    "analytics.view",
    "activity.view",
    "searches.view",
  ],
  hr: [
    "dashboard.view",
    "staff.view",
    "staff.manage",
    "hr.view",
    "hr.manage",
    "activity.view",
  ],
  analyst: [
    "dashboard.view",
    "products.view",
    "orders.view",
    "customers.view",
    "support.view",
    "marketing.view",
    "finance.view",
    "analytics.view",
    "settings.view",
    "activity.view",
    "searches.view",
  ],
};

export const ROLE_META: Record<
  StaffRole,
  { label: string; description: string; accent: string }
> = {
  super_admin: {
    label: "Super Admin",
    description: "Full control of the platform, staff, and settings.",
    accent: "bg-neutral-900 text-white",
  },
  admin: {
    label: "Administrator",
    description: "Broad operational control across the business.",
    accent: "bg-violet-100 text-violet-700",
  },
  manager: {
    label: "Operations Manager",
    description: "Oversees catalog, orders, customers, and support.",
    accent: "bg-blue-100 text-blue-700",
  },
  support_agent: {
    label: "Support Agent",
    description: "Helpdesk, customer assistance, and order lookups.",
    accent: "bg-emerald-100 text-emerald-700",
  },
  marketing: {
    label: "Marketing",
    description: "Promotions, deals, featured products, and campaigns.",
    accent: "bg-amber-100 text-amber-700",
  },
  fulfillment: {
    label: "Fulfillment",
    description: "Order processing, inventory, and shipping management.",
    accent: "bg-cyan-100 text-cyan-700",
  },
  finance: {
    label: "Finance",
    description: "Revenue, expenses, refunds, and financial reporting.",
    accent: "bg-emerald-100 text-emerald-800",
  },
  hr: {
    label: "Human Resources",
    description: "Employee records, roles, departments, and compliance.",
    accent: "bg-pink-100 text-pink-700",
  },
  analyst: {
    label: "Analyst",
    description: "Read-only access to dashboards and reports.",
    accent: "bg-neutral-200 text-neutral-700",
  },
};
